name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  sample:
    required: false
    description: 'input description here'
    default: 'default value if applicable'
  match:
    required: false
    description: 'filter stream names matching a pattern'
runs:
  using: 'node12'
  main: 'dist/index.js'
