name: 'Kinesis Stream List'
description: 'Outputs a list of kinesis streams'
author: 'Kerry Sheldon'
inputs:
  match:
    required: false
    description: 'filter stream names matching a pattern'
outputs:
  streamNames: # id of the output
    description: 'A comma separated list of stream names (matching pattern if provided)'
runs:
  using: 'node16'
  main: 'dist/index.js'
